name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Compilar com make
        run: make

      - name: Verificar se o executável foi gerado
      ear run: test -f texas_holdemname: Build on: push: branches: [ "master" ] pull_request: branches: [ "master" ] jobs: build: runs-on: ubuntu-latest steps: - name: Checkout do codigo uses: actions/checkout@v4 - name: Compilar com make run: make - name: Verificar se o executavel foi gerado run: test -f texas_holdem
